spring.application.name=badwallet-api

# Configuration base de données MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/badwallet_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# Serveur sur port 8080
server.port=8080
server.error.include-message=always
server.error.include-binding-errors=always

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# URL du payment-service externe (port 8081)
payment.service.url=http://localhost:8081

# Async config
spring.task.execution.pool.core-size=4
spring.task.execution.pool.max-size=8
