spring.application.name=payment-service

# Configuration base de données PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/payment_db
spring.datasource.username=postgres
spring.datasource.password=amina2003@
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuration JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Serveur sur port 8081
server.port=8081
server.error.include-message=always
server.error.include-binding-errors=always

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false
